# Config para air hot reload
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o main -buildvcs=false ."
  bin = "main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  build = "green"
  runner = "magenta"

